First press release
OpenSoftwareMovement/language_crowdsource pull request #11
Opened 2023-12-05 20:00 UTC by rigole

I tried to follow the instructions on the README, I succed the frontend but got a problem 
after creating the docker-compose.yml to run the Docker compose-up command

2023-12-06 18:08 UTC, math-alpha requested changes
Dear @rigole thanks for your PR.

However, the issue yoU are trying to solve is not very clear.

For setup, simply run the "./setup.sh" script in a bash terminal.

@giftcup please care to update the README.md to ease the setup of new contributors.

2023-12-06 18:08 UTC, math-alpha commented on frontend/tsconfig.json
Please avoid adding formatting changes to origin

2023-12-06 18:08 UTC, math-alpha commented on backend/docker-compose.yml
We already have a compose file here `configs/docker-compose.yml`

Also, we use .env files to store secrets to avoid leaks ;)

2023-12-07 14:49 UTC, rigole commented on frontend/tsconfig.json
I didn't make any change. Don't worry

2023-12-07 14:49 UTC, closed without merging

2023-12-07 14:52 UTC, rigole commented on frontend/tsconfig.json
I tried to open the bash file with a linux terminal. I succeeded to open the setup but the start.sh Docker told me that they are some file not compatible with Linux. I tried to run the docker-compose on widows but still issue with some missing libraries or something like that. But the frontend is okay. I am still trying to solve the problem

2023-12-07 14:56 UTC, math-alpha commented on frontend/tsconfig.json
`setup.sh` not `start.sh`

2023-12-07 14:59 UTC, rigole commented on frontend/tsconfig.json
Yes yes that what I did and  the setup.sh includes an instruction to run the start.sh

2023-12-07 15:05 UTC, math-alpha commented on frontend/tsconfig.json
Can you paste a screenshot of what you have when you run the `setup.sh` file?

2023-12-07 15:07 UTC, rigole commented on frontend/tsconfig.json
Okay. I closed the Linux terminal but I soon as I tried I will send